service: sls-api # NOTE: update this with your service name
custom:
  dynamodb:
    start:
      port: 8000
      migrate: true # please create the tables
      inMemory: true
      onStart: true
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
plugins:
  - serverless-offline
  - serverless-dynamodb-local
functions:
  hello:
    handler: handler.hello
  jobs:
    handler: src/jobs/handler.handler
  listJobs:
    handler: src/jobs/list.handler
    events:
      - http:
          method: GET
          path: /jobs
  createJob:
    handler: src/jobs/create.handler
    events:
      - http:
          method: POST
          path: /jobs
  getJob:
    handler: src/jobs/findOne.handler
    events:
      - http:
          method: GET
          path: /jobs/{id}
resources:
  Resources:
    JobsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "sls-api-jobs"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
